<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="TopupAggregate\Events\" />
    <Folder Include="TopupAggregate\Exceptions\" />
    <Folder Include="TopupAggregate\Specifications\" />
    <Folder Include="Services\" />
    <Folder Include="Repositories\" />
    <Folder Include="TopupTransaction\" />
  </ItemGroup>

</Project>
