<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PSP.SharedKernel</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PSP.Contracts\PSP.Contracts.csproj" />
  </ItemGroup>

</Project>
