<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PSP.Contracts\PSP.Contracts.csproj" />
    <ProjectReference Include="..\PSP.SharedKernel\PSP.SharedKernel.csproj" />
    <ProjectReference Include="..\PSP.Topup.Domain\PSP.Topup.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\" />
    <Folder Include="Handlers\" />
    <Folder Include="Behaviors\" />
    <Folder Include="DTOs\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Mapping\" />
    <Folder Include="Events\" />
    <Folder Include="Validators\" />
    <Folder Include="Queries\" />
  </ItemGroup>

</Project>
