<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MediatR" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    </ItemGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\PSP.Contracts\PSP.Contracts.csproj" />
    <ProjectReference Include="..\PSP.SharedKernel\PSP.SharedKernel.csproj" />
    <ProjectReference Include="..\PSP.Topup.Domain\PSP.Topup.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Topup\Commands\" />
    <Folder Include="Features\Topup\" />
    <Folder Include="Handlers\" />
    <Folder Include="Behaviors\" />
    <Folder Include="Features\Topup\DTOs\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Mapping\" />
    <Folder Include="Features\Topup\Events\" />
    <Folder Include="Features\Topup\Validators\" />
    <Folder Include="Features\Topup\Queries\" />
  </ItemGroup>

</Project>
