<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>PSP.Topup.Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\PSP.Contracts\PSP.Contracts.csproj" />
        <ProjectReference Include="..\PSP.Messaging\PSP.Messaging.csproj" />
        <ProjectReference Include="..\PSP.SharedKernel\PSP.SharedKernel.csproj" />
        <ProjectReference Include="..\PSP.Topup.Application\PSP.Topup.Application.csproj" />
        <ProjectReference Include="..\PSP.Topup.Domain\PSP.Topup.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Contracts\" />
        <Folder Include="Logging\" />
        <Folder Include="Caching\" />
        <Folder Include="Exceptions\" />
        <Folder Include="Messaging\Configuration\" />
        <Folder Include="Messaging\Publishers\" />
        <Folder Include="Options\" />
        <Folder Include="Resilience\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MassTransit" />
      <PackageReference Include="MassTransit.RabbitMQ" />
      <PackageReference Include="Microsoft.Extensions.Http" />
      <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
      <PackageReference Include="Polly" />
      <PackageReference Include="Polly.Extensions.Http" />
    </ItemGroup>

</Project>
